---
name: Deployer

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to production
        run: echo DEPLOYING "${GITHUB_REF##*/}" TO PRODUCTION AAAAAAHHHH
