---
name: Deployer

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to production
        run: echo DEPLOYING "${TAG}" TO PRODUCTION AAAAAAHHHH
        env:
          TAG: ${{GITHUB_REF##*/}}
