---
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Get the Date
        run: echo "::set-env name=tag::$(date '+%Y%m%d.%H%M.%S')"
      - name: tag it up
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{ tag }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy to production
        run: echo DEPLOYING "${tag}" TO PRODUCTION AAAAAAHHHH
        env:
          tag: ${GITHUB_REF##*/}
